# Exported from Render on 2025-12-07T15:50:20Z
version: "1"
projects:
- name: MealEase
  environments:
  - name: Production
    services:
    - type: web
      name: MealEase
      runtime: node
      repo: https://github.com/RossbeilK/MealEase
      branch: yanlu_update_part4
      plan: free
      region: virginia
      buildCommand: yarn
      startCommand: npm run start
      autoDeployTrigger: commit
